spring:
  application:
    name: config
  rabbitmq:
    host: 47.103.4.35
    port: 5672
    username: admin
    password: admin
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Charlie-smith/whu-config
          username: 1327987604@qq.com
          password: 19981021Li
          basedir: /opt/config/
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

